[package]
name = "dxbcross"
version = "0.1.0"
authors = ["Felix Kaaman <trundmatu@gmail.com>"]

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
dxbc = { path = "../dxbc" }
rspirv = "0.11.0"
spirv_headers = "1.5.0"

[dev-dependencies]
pretty-hex = "0.2.1"
rspirv = "0.11.0"
