[package]
name = "dxbcc"
version = "0.1.0"
authors = ["Felix Kaaman <trundmatu@gmail.com>"]

[dependencies]
bitflags = "1"
byteorder = "1"
dxbc = { path = "../dxbc" }

[dev-dependencies]
byteorder = "1"
rspirv = "0.5"
pretty-hex = "0.1"
